---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gateway-secret
  namespace: default
spec:
  encryptedData:
    SECRET_KEY: AgC4EPvRQ4QZ0459x5F70D2svQIZiYfxT/FrFgOIGUQgMMdbgJUU7wRVkziBlW1bfZcdho/g4em47VbNSpdqI/t4i4QhulOcR87BDRScJ+wfiABY3VfrXJlAxPfIe3NNT9STJmae2GYFCUiDgeJ6pGbgDh+wvXz8cPkepnVYTpxAqvepzTSd0PrnYoySPEOKbepPegFWGPaTP8RkNyt/1jCFLeOPaBzoMfQYGnSX/7bKWw2vX+McvcXBI2jp+0RgQwuGnPXjJx1wfVFD9OJlwsq5Lny1w/JZmyw86Wem3a5re7SqSdBBgazaQV3HPXQVsuznLqQm75W2TVgu9p8Mqt2ur6uqpW2V7C+H0/V0M2Qxju3z/Np1ROPpWitEJ9//1YHzx2cmNmkTDhEBZOWshe3NdzAh4HZ4m8QI3aQ4WPveRhl5yl5/E/8fqzxLjn4+uDalSXTYHmZcMSO09B+2UZj/KZ9G6mAJaU8cg+ggSq5VTom0/b+CptLhApOJvemUzoq6fL21U7V5eKKB5x5+amN8NxLloD1KAwVr/MvAG4gBxw+VeF5Ha3I1TbErfpST02QZD4e6qUtdp5mR3qoe7madx7EBKluFnxNUCy6L4+XhrQQRE3X9EVqen87lzEPdoxG83FBqkZ4yB7u2948S7O/ZBgwdk00hr+mKcYx3gi/0YQJCAiSNM3xvYqgYs6F8hlAr6G93zHA3m4X9khg8ZBAuTOiIk2Jdrb0TbythGD1qNoYlNRTk
  template:
    metadata:
      name: gateway-secret
      namespace: default
    type: Opaque
